/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

const { blocks, data } = wp;
const { withSelect } = data;
const { getBlockType } = blocks;
function BlockTitle(_ref) {
  const { name } = _ref;
  if (!name) {
    return null;
  }
  const blockType = getBlockType(name);
  if (!blockType) {
    return null;
  }
  return blockType.title;
}
Object.defineProperty(wp.blockEditor, "BlockTitle", {
  get: withSelect((select, ownProps) => {
    const _select = select("core/block-editor");
    const { getBlockName } = _select;
    const { clientId } = ownProps;
    return {
      name: `${getBlockName(clientId)} - from Drupal!!!`
    };
  })(BlockTitle)
});
