/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

(function(wp2, Drupal2) {
  const { blocks, blockEditor, data } = wp2;
  const { compose } = wp2.compose;
  const { withSelect } = data;
  const { registerBlockType } = blocks;
  const { InnerBlocks } = blockEditor;
  const style = {
    minHeight: "40px",
    margin: "0 -40px",
    padding: "0 40px"
  };
  const template = [["core/paragraph", {}]];
  function SectionEdit() {
    return /* @__PURE__ */ React.createElement("main", { style }, /* @__PURE__ */ React.createElement(InnerBlocks, { templateLock: false, template }));
  }
  const settings = {
    title: Drupal2.t("Section"),
    description: Drupal2.t("Section block for template use."),
    icon: "media-document",
    attributes: {},
    supports: {
      inserter: false,
      align: true,
      html: false
    },
    edit: compose([
      withSelect((select, { clientId }) => {
        const { getBlock } = select("core/block-editor");
        const block = getBlock(clientId);
        return {
          hasInnerBlocks: !!(block && block.innerBlocks.length)
        };
      })
    ])(SectionEdit),
    save({ className }) {
      return /* @__PURE__ */ React.createElement("main", { className }, /* @__PURE__ */ React.createElement(InnerBlocks.Content, null));
    }
  };
  registerBlockType(`drupal/section`, { category: "common", ...settings });
})(wp, Drupal);
