/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

(function(wp2) {
  const { components, editPost } = wp2;
  const { Fragment } = wp2.element;
  const { PanelBody } = components;
  const { PluginSidebar, PluginSidebarMoreMenuItem } = editPost;
  function AdditionalFieldsPluginSidebar() {
    return /* @__PURE__ */ React.createElement(Fragment, null, /* @__PURE__ */ React.createElement(PluginSidebarMoreMenuItem, { target: "gutenberg-boilerplate-sidebar" }, "Gutenberg Boilerplate"), /* @__PURE__ */ React.createElement(
      PluginSidebar,
      {
        name: "additional-fields",
        title: "Additional fields",
        icons: "forms",
        isPinnable: "false"
      },
      /* @__PURE__ */ React.createElement(PanelBody, null)
    ));
  }
  window.DrupalGutenberg = window.DrupalGutenberg || {};
  window.DrupalGutenberg.Plugins = window.DrupalGutenberg.Plugins || {};
  window.DrupalGutenberg.Plugins.AdditionalFieldsPluginSidebar = AdditionalFieldsPluginSidebar;
})(wp);
