/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

((wp2, Drupal2, DrupalGutenberg2) => {
  const {
    MediaLibrary,
    withNativeDialog,
    withGutenbergDialog
  } = DrupalGutenberg2.Components;
  wp2.hooks.addFilter(
    "editor.MediaUpload",
    "core/edit-post/components/media-upload/replace-media-upload",
    () => Drupal2.isMediaLibraryEnabled() ? withNativeDialog(MediaLibrary) : withGutenbergDialog(MediaLibrary)
  );
  wp2.hooks.addFilter(
    "editor.MediaReplaceFlow",
    "core/edit-post/components/media-replace-flow/replace-media-replace-flow",
    (Component) => {
      return (props) => /* @__PURE__ */ React.createElement(
        Component,
        {
          ...props,
          onToggleFeaturedImage: false
        }
      );
    }
  );
  wp2.hooks.addFilter(
    "editor.MediaPlaceholder",
    "core/edit-post/components/media-placeholder/replace-media-placeholder",
    (Component) => {
      return (props) => /* @__PURE__ */ React.createElement(
        Component,
        {
          ...props,
          onToggleFeaturedImage: false
        }
      );
    }
  );
})(wp, Drupal, DrupalGutenberg, drupalSettings);
