/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

((wp2) => {
  const { element, plugins, editPost, data } = wp2;
  const { dispatch, select } = data;
  const { useRef, useEffect } = element;
  const { registerPlugin } = plugins;
  const { PluginDocumentSettingPanel } = editPost;
  const FormPanel = () => {
    const ref = useRef(null);
    useEffect(() => {
      const editAdvanced = document.getElementById("edit-advanced");
      const sidebar = document.getElementById("gutenberg-sidebar");
      if (editAdvanced) {
        ref.current.appendChild(editAdvanced);
      }
      return () => {
        if (editAdvanced && sidebar) {
          sidebar.appendChild(editAdvanced);
        }
      };
    }, []);
    return /* @__PURE__ */ React.createElement("div", { ref });
  };
  const NodeDocumentSettings = () => /* @__PURE__ */ React.createElement(
    PluginDocumentSettingPanel,
    {
      name: "panel",
      className: "node-settings-plugin",
      title: "Node"
    },
    /* @__PURE__ */ React.createElement(FormPanel, null)
  );
  registerPlugin("node-document-settings", {
    render: NodeDocumentSettings,
    icon: null
  });
  const isOpened = select("core/edit-post").isEditorPanelOpened(
    "node-document-settings/panel"
  );
  if (!isOpened) {
    dispatch("core/edit-post").toggleEditorPanelOpened(
      "node-document-settings/panel"
    );
  }
})(wp, Drupal);
