/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

((wp2) => {
  const { registerPlugin } = wp2.plugins;
  const { dispatch } = wp2.data;
  const { createSlotFill, MenuItem } = wp2.components;
  const { __ } = wp2.i18n;
  const { Fill: ToolsMoreMenuGroup } = createSlotFill("ToolsMoreMenuGroup");
  function toggleWelcomeGuide() {
    dispatch("core/edit-post").toggleFeature("welcomeGuideDrupalDisabled");
  }
  const DrupalToolsMenu = () => /* @__PURE__ */ React.createElement(ToolsMoreMenuGroup, null, /* @__PURE__ */ React.createElement(MenuItem, { role: "menuitem", onClick: () => toggleWelcomeGuide }, __("Welcome Guide")), /* @__PURE__ */ React.createElement(
    MenuItem,
    {
      role: "menuitem",
      href: "https://www.drupal.org/docs/8/modules/gutenberg",
      target: "_new"
    },
    __("Help")
  ));
  registerPlugin("more-menu-item-test", { render: DrupalToolsMenu });
})(wp);
